server:
  port: 8672
spring:
  application:
    name: service-provider-heartfailure
  datasource:
    url: jdbc:mysql://localhost:3306/gi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1998918Jyc
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/
